# This is a basic workflow to help you get started with Actions

name: CI

on: [push]

jobs:
  test:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Cache Node Modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}
            ${{ runner.os }}-build
            ${{ runner.os }}
            
      - name: Install Dependencies
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
        run: npm i
      
      - name: Check Lint
        run: npm run lint
      
      - name: Run Build
        run: npm run build
      
      - name: Run Jest Test
        run: npm run test

      - name: Integration - dappeteer
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: "true"
        with:
          args: node -v && npm run integration:dappeteer
